NEWS_API_KEY = "pub_ac61d3e70aef4dd9a61669cb6ed7ef44"
NEWS_PROVIDER = "auto"
TOP_N_STOCKS = 12
TOP_N_SECTOR_STOCKS = 7

STOCK_SEARCH_TERMS = {
	"HDFCBANK": "HDFC Bank",
	"ICICIBANK": "ICICI Bank",
	"KOTAKBANK": "Kotak Mahindra Bank",
	"BAJFINANCE": "Bajaj Finance",
	"BAJAJFINSV": "Bajaj Finserv",
	"INFY": "Infosys",
	"HCLTECH": "HCL Technologies",
	"TECHM": "Tech Mahindra",
	"PERSISTENT": "Persistent Systems",
	"RELIANCE": "Reliance Industries",
	"HINDUNILVR": "Hindustan Unilever",
	"M&M": "Mahindra and Mahindra",
	"HEROMOTOCO": "Hero MotoCorp",
	"EICHERMOT": "Eicher Motors",
	"SUNPHARMA": "Sun Pharma",
	"DRREDDY": "Dr Reddy",
	"DIVISLAB": "Divi's Laboratories",
	"AUROPHARMA": "Aurobindo Pharma",
	"TORNTPHARM": "Torrent Pharma",
	"TATASTEEL": "Tata Steel",
	"JSWSTEEL": "JSW Steel",
	"HINDALCO": "Hindalco",
	"ULTRACEMCO": "UltraTech Cement",
	"DMART": "Avenue Supermarts",
	"NAUKRI": "Info Edge",
	"POLICYBZR": "PB Fintech Policybazaar",
}

SECTOR_STOCKS = {
	"BANKING": ["HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK", "BAJFINANCE", "BAJAJFINSV"],
	"IT": ["TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "PERSISTENT", "COFORGE"],
	"ENERGY": ["RELIANCE", "ONGC", "NTPC", "POWERGRID", "ADANIENT", "ADANIGREEN", "ADANIPOWER"],
	"FMCG": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "DABUR", "GODREJCP", "COLPAL"],
	"AUTO": ["MARUTI", "TATAMOTORS", "M&M", "HEROMOTOCO", "EICHERMOT", "TVSMOTOR", "ASHOKLEY"],
	"PHARMA": ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "LUPIN", "AUROPHARMA", "TORNTPHARM"],
	"METALS": ["TATASTEEL", "JSWSTEEL", "HINDALCO", "GRASIM", "ULTRACEMCO", "SIEMENS", "ABB"],
	"CONSUMPTION": ["ZOMATO", "PAYTM", "POLICYBZR", "NAUKRI", "INDIAMART", "DMART", "TRENT"],
}

STOCKS = [

# BANKING & FINANCIALS (7)
"HDFCBANK","ICICIBANK","SBIN","KOTAKBANK","AXISBANK","BAJFINANCE","BAJAJFINSV",

# IT (7)
"TCS","INFY","HCLTECH","WIPRO","TECHM","PERSISTENT","COFORGE",

# ENERGY & POWER (7)
"RELIANCE","ONGC","NTPC","POWERGRID","ADANIENT","ADANIGREEN","ADANIPOWER",

# FMCG (7)
"HINDUNILVR","ITC","NESTLEIND","BRITANNIA","DABUR","GODREJCP","COLPAL",

# AUTO (7)
"MARUTI","TATAMOTORS","M&M","HEROMOTOCO","EICHERMOT","TVSMOTOR","ASHOKLEY",

# PHARMA (7)
"SUNPHARMA","DRREDDY","CIPLA","DIVISLAB","LUPIN","AUROPHARMA","TORNTPHARM",

# METALS & INDUSTRIALS (7)
"TATASTEEL","JSWSTEEL","HINDALCO","GRASIM","ULTRACEMCO","SIEMENS","ABB",

# CONSUMPTION / INTERNET (7)
"ZOMATO","PAYTM","POLICYBZR","NAUKRI","INDIAMART","DMART","TRENT"

]